# Generated by Django 3.1.4 on 2021-01-16 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Başlık', models.CharField(max_length=50, verbose_name='başlık')),
                ('resim', models.ImageField(upload_to='', verbose_name='ana resim')),
                ('resim2', models.ImageField(blank=True, upload_to='', verbose_name='detay resim')),
                ('metin', ckeditor.fields.RichTextField(verbose_name='metin alanı')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
