# Generated by Django 3.1.4 on 2021-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='genre',
            field=models.CharField(default=1, max_length=40, verbose_name='Tür'),
            preserve_default=False,
        ),
    ]
