# Generated by Django 3.1.4 on 2021-01-06 22:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoabouttek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoname', models.CharField(max_length=100, verbose_name='Konu Bilginin')),
                ('infotext', ckeditor.fields.RichTextField(verbose_name='Konunun yazısı')),
                ('infoshort', models.CharField(max_length=100, verbose_name='konunun kısa özeti')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteday', models.CharField(max_length=120, verbose_name='Günün sözü')),
                ('quoteown', models.CharField(max_length=50, verbose_name='sözün sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlık')),
                ('genre', models.CharField(max_length=40, verbose_name='Tür')),
                ('step1', models.CharField(max_length=120, verbose_name='adım 1')),
                ('imgfield', models.ImageField(blank=True, upload_to='', verbose_name='Resim alanı')),
                ('text1', ckeditor.fields.RichTextField(verbose_name='metin 1')),
                ('step2', models.CharField(blank=True, max_length=120, verbose_name='adım 2')),
                ('imgfield2', models.ImageField(blank=True, upload_to='', verbose_name='Resim alanı 2')),
                ('text2', ckeditor.fields.RichTextField(blank=True, verbose_name='metin 2')),
                ('step3', models.CharField(max_length=120, verbose_name='adım 3')),
                ('imgfield3', models.ImageField(blank=True, upload_to='', verbose_name='Resim alanı 3')),
                ('text3', ckeditor.fields.RichTextField(verbose_name='metin 3')),
                ('step4', models.CharField(max_length=120, verbose_name='adım 4')),
                ('imgfield4', models.ImageField(blank=True, upload_to='', verbose_name='Resim alanı 4')),
                ('text4', ckeditor.fields.RichTextField(verbose_name='metin 4')),
                ('step5', models.CharField(max_length=120, verbose_name='adım 5')),
                ('imgfield5', models.ImageField(blank=True, upload_to='', verbose_name='Resim alanı 5')),
                ('text5', ckeditor.fields.RichTextField(verbose_name='metin 5')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
