# Generated by Django 3.1.4 on 2021-01-25 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text4',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='metin 4'),
        ),
    ]
