# Generated by Django 3.1.4 on 2021-01-06 23:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210107_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text6',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='metin 6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text5',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='metin 5'),
        ),
    ]
