# Generated by Django 3.1.4 on 2021-01-07 19:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210107_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='step1',
            field=models.CharField(blank=True, max_length=120, verbose_name='adım 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='step3',
            field=models.CharField(blank=True, max_length=120, verbose_name='adım 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='step4',
            field=models.CharField(blank=True, max_length=120, verbose_name='adım 4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='step5',
            field=models.CharField(blank=True, max_length=120, verbose_name='adım 5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=ckeditor.fields.RichTextField(verbose_name='ana metin'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='metin 1'),
        ),
    ]
