# Generated by Django 3.1.4 on 2021-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210107_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('userimage', models.ImageField(upload_to='', verbose_name='kullanının resmi')),
                ('userrealname', models.CharField(max_length=100, verbose_name="kullanıcın gerçek ad-soyad'ı ")),
            ],
        ),
        migrations.AlterField(
            model_name='infoabouttek',
            name='infoname',
            field=models.CharField(max_length=100, verbose_name='Bilginin konusu'),
        ),
    ]
