# Generated by Django 3.1.4 on 2021-01-06 23:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_infoabouttek_infoshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text5',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='metin 6'),
        ),
    ]
